# WorkExo Analysis

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sn

In [2]:
#importing datasets
data1 = pd.read_csv("./datasets/workers1.csv")
data2 = pd.read_csv("./datasets/workers2.csv")
data3 = pd.read_csv("./datasets/workers3.csv")
data4 = pd.read_csv("./datasets/workers4.csv")
data5 = pd.read_csv("./datasets/workers5.csv")
data6 = pd.read_csv("./datasets/workers6.csv")
data7 = pd.read_csv("./datasets/workers7.csv")
data8 = pd.read_csv("./datasets/workers8.csv")
data9 = pd.read_csv("./datasets/workers9.csv")
data10 = pd.read_csv("./datasets/workers10.csv")
data11 = pd.read_csv("./datasets/workers11.csv")
data12 = pd.read_csv("./datasets/workers12.csv")
data13 = pd.read_csv("./datasets/workers13.csv")
data14 = pd.read_csv("./datasets/workers14.csv")
data15 = pd.read_csv("./datasets/workers15.csv")

In [3]:
# Concat all the datasets into one single dataset 
data = pd.concat([data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15]) 

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15000 entries, 0 to 999
Data columns (total 6 columns):
worker_id                    15000 non-null int64
work_type                    15000 non-null int64
no_of_workers                15000 non-null int64
time_takes_by_each_worker    15000 non-null int64
complete_work_duration       15000 non-null int64
rating                       15000 non-null float64
dtypes: float64(1), int64(5)
memory usage: 820.3 KB


In [5]:
data.shape

(15000, 6)

In [6]:
data.head()

worker_id  work_type  no_of_workers  time_takes_by_each_worker  \
0          1          7              2                          5   
1          2          5              7                          8   
2          3          2             10                          5   
3          4          3             10                          9   
4          5          5              8                          7   

   complete_work_duration  rating  
0                       7     3.5  
1                       6     1.8  
2                      10     2.0  
3                       9     3.8  
4                       5     3.1

In [7]:
#distributing independent and dependent variables
X = data.iloc[:,1:4].values
y = data.iloc[:,5].values

In [8]:
#independent variable
print(X)

[[ 7  2  5]
 [ 5  7  8]
 [ 2 10  5]
 ...
 [ 4  1  7]
 [ 7  3 10]
 [ 6  1  7]]


In [9]:
#Splitting the dataset into Training and Test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [10]:
#FItting linear regresion model in the Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
#Predicting the Test Set Results
y_pred = regressor.predict(X_test)

In [12]:
#Predicted data
print(y_pred)

[2.98152364 3.03678716 3.01677124 ... 3.01496307 3.02132629 3.01003949]


In [13]:
#Actual test set data
print(y_test)

[4.  1.  3.8 ... 4.2 4.2 4.2]
